export const ADD_ONS = [
  { id: 'uplighting', name: 'Uplighting', description: 'Color-changing LED uplighting for venue mood' },
  { id: 'neonlighting', name: 'Neon Uplighting', description: 'Vibrant neon cyan, pink & purple lighting — next-level energy', isPremium: true },
  { id: 'secondmic', name: 'Second Microphone', description: 'Extra wireless mic for toasts & announcements' },
  { id: 'dancing', name: 'Desi Dancing Coach', description: 'Live dance coaching session (30 min)' },
  { id: 'photobooth', name: 'Photo Booth Setup', description: 'Photo booth music & transitions' },
  { id: 'livedrums', name: 'Live Drums', description: 'Add live dhol player for select songs' },
  { id: 'mcsetup', name: 'Full MC Setup', description: 'Professional MC service with DJ coordination' },
] as const

export const EVENTS = [
  {
    id: 'sangeet',
    name: 'Sangeet',
    description:
      'The night that sets the tone for everything after. Deep Bhangra, peak Bollywood, and the kind of floor your family will still be talking about at the next wedding.',
    details: 'The Sangeet is where the weekend really starts. I mix peak-energy Bhangra with Bollywood hits and keep the floor packed from the first song — live mic transitions, crowd reads, and sets built around your family, not a playlist off the shelf. Every cousin, every generation, same dance floor.',
    badge: 'Most Booked',
    badgeColor: 'bg-daula-red text-daula-white',
    included: ['3–5 hour set', 'Full sound system', 'Custom Bhangra/Bollywood set', 'Live mic transitions'],
    imgSrc: '/event-sangeet.png',
    imgAlt: 'Sangeet dance floor — DJ Daula behind the decks with vibrant stage lighting',
    accentLabel: 'Bhangra · Bollywood',
    suggestedAddOns: ['uplighting', 'neonlighting', 'secondmic', 'livedrums'],
  },
  {
    id: 'reception',
    name: 'Wedding Reception',
    description:
      'Every table, every generation, one dance floor. From first dance to peak-hour chaos — Hip-Hop, Top 40, Bollywood, R&B, all in one night.',
    details: 'The reception is the grand finale. I coordinate your first dance, read the room across every table, and build from the early sets into peak-hour floor energy. Open-format mixing means the playlist responds to your crowd in real time — not a pre-loaded set that ignores what\'s actually happening on the floor.',
    badge: null,
    badgeColor: '',
    included: ['4–6 hour set', 'Full sound system', 'First dance coordination', 'Open-format mixing'],
    imgSrc: '/event-reception.png',
    imgAlt: 'Wedding reception dance floor lit up with glow sticks',
    accentLabel: 'Hip-Hop · R&B · Open Format',
    suggestedAddOns: ['uplighting', 'neonlighting', 'secondmic', 'mcsetup'],
  },
  {
    id: 'mehndi',
    name: 'Mehndi / Dholki',
    description:
      'Intimate but alive. I keep the energy right while henna flows and the family warms up for the weekend ahead — not too quiet, never too much.',
    details: "The Mehndi has its own rhythm. Henna artists, aunties catching up, cousins testing out their moves. I keep the background warm and hit the peak moments when the room's ready — never letting the floor go cold or tipping into chaos before the Sangeet.",
    badge: null,
    badgeColor: '',
    included: ['2–4 hour set', 'Sound system', 'Coordinated playlist pacing', 'Family-friendly format'],
    imgSrc: '/event-mehndi.png',
    imgAlt: 'Mehndi evening — guests in vibrant traditional attire celebrating together',
    accentLabel: 'Mehndi · Dholki',
    suggestedAddOns: ['uplighting', 'neonlighting', 'livedrums', 'dancing'],
  },
  {
    id: 'engagement',
    name: 'Engagement Party',
    description:
      'The first celebration of many. Lock in the vibe early with a set that brings every background and generation together — so everyone leaves already excited for the weekend ahead.',
    details: "Your engagement is the preview. I blend musical tastes from everyone in the room — Desi, Western, or both — so every guest feels like this weekend was built for them. First impression matters, and the dance floor is how you make it.",
    badge: null,
    badgeColor: '',
    included: ['2–4 hour set', 'Sound system', 'Mixed-audience format', 'Custom playlist consultation'],
    imgSrc: '/event-engagement.png',
    imgAlt: 'Engagement party — DJ setup overlooking a packed ballroom',
    accentLabel: 'Mixed · Open Format',
    suggestedAddOns: ['uplighting', 'neonlighting', 'photobooth'],
  },
  {
    id: 'full-weekend',
    name: 'Full Weekend Package',
    description:
      'One DJ across every night of your wedding weekend. No handoffs, no re-explaining your family to someone new — just me, reading the same crowd from Mehndi through the last song of the reception.',
    details: 'Book me for the whole weekend and you get continuity. Same voice, same transitions, same energy. Your family recognizes me by the second night. I handle the backstage coordination across every event — one person who already knows how your crowd moves.',
    badge: 'Best Value',
    badgeColor: 'bg-daula-gold text-daula-black',
    included: ['All events covered', 'Consistent DJ across every night', 'Custom set planning per event', 'Priority booking'],
    imgSrc: '/event-full-weekend.png',
    imgAlt: 'Full wedding weekend — guests dancing at a traditional celebration',
    accentLabel: 'All Events · One DJ',
    suggestedAddOns: ['uplighting', 'neonlighting', 'secondmic', 'mcsetup', 'livedrums'],
  },
] as const
